name: github_repo_viewer_oauth2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  auto_route: ^5.0.2
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_getit: ^1.2.1
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.0.0
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  material_design_icons_flutter: ^5.0.6996
  material_floating_search_bar: ^0.3.7
  oauth2: ^2.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  sembast: ^3.3.1
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  webview_flutter: ^3.0.4

dev_dependencies:
  auto_route_generator: null
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: null
  json_serializable: ^6.5.1
  lint: ^1.10.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
